---
- name: Load Infiniband kernel drivers
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - mlx5_core
    - mlx5_ib
    - ib_core
    - ib_uverbs
    - ib_ipoib
    - rdma_cm
    - rdma_ucm

- name: Bring up the Infiniband interfaces
  command: ifconfig ib0 up
  ignore_errors: True
