---
# Base configuration for all servers to enable net access
- name: Enable HTTP access via proxy
  lineinfile:
    path: "/etc/environment"
    create: yes
    mode: 0644
    owner: root
    group: root
    line: "{{ item }}"
  become: True
  with_items:
  - "http_proxy={{ phe_http_proxy }}"
  - "https_proxy={{ phe_http_proxy }}"

- name: Add proxy settings as profile
  copy:
    dest: "/etc/profile.d/phe_proxy.sh"
    mode: 0755
    owner: root
    group: root
    content: |
      export http_proxy={{ phe_http_proxy }}
      export https_proxy={{ phe_http_proxy }}
  become: True

- name: Add proxy settings as profile
  copy:
    dest: "/etc/sudoers.d/proxy"
    mode: 0644
    owner: root
    group: root
    content: |
      Defaults env_keep += "http_proxy https_proxy"
  become: True
