---
pkgdeps:
  nfs_server:
    - "nfs-utils"
  nfs_client: []
  openstack_repo:
    - "centos-release-openstack-pike"
  openstack_client:
    - "python-devel"
    - "python-virtualenv"
    - "python-openstackclient"
    - "python-heatclient"
    - "python-barbicanclient"
  user_env:
    - "vim"
    - "git"
    - "gcc"

ca_cert_path: "/etc/pki/ca-trust/source/anchors"
ca_cert_cmd: "update-ca-trust extract"

# POSIX User groups
system_sudo_group: "wheel"
