---
# This name is used for the Heat stack and as a prefix for the
# cluster node hostnames.
cluster_name: stig

# Multi-node application topology.  In this case we have a SLURM
# deployment formed from a login/controller node and a number of
# batch compute nodes.
cluster_groups:
  - "{{ infra_net }}"
  - "{{ infra_data }}"
  - "{{ infra_user }}"
  - "{{ infra_dib }}"
  - "{{ infra_manageiq }}"

infra_net:
  name: "net"
  flavor: "m1.small"
  image: "CentOS-7-1708"
  user: "centos"
  num_nodes: 1

infra_data:
  name: "data"
  flavor: "m1.small"
  image: "CentOS-7-1708"
  user: "centos"
  num_nodes: 1

infra_user:
  name: "user"
  flavor: "m1.small"
  image: "Debian-9.1.1-Stretch"
  user: "debian"
  num_nodes: 1

infra_dib:
  name: "dib"
  flavor: "m1.small"
  image: "CentOS-7-1708"
  user: "centos"
  num_nodes: 1

infra_manageiq:
  name: "manageiq"
  flavor: "m1.small"
  image: "CentOS-7-1708"
  user: "centos"
  num_nodes: 1

cluster_roles: 
  - name: "phe_user"
    groups: 
      - "{{ infra_user }}"
      - "{{ infra_dib }}"
  - name: "phe_data"
    groups:
      - "{{ infra_data }}"
  - name: "phe_net"
    groups:
      - "{{ infra_net }}"
  - name: "phe_manageiq"
    groups:
      - "{{ infra_manageiq }}"
