---
# Base configuration for all servers to enable net access
- hosts: cluster
  tasks:
  - name: Enable HTTP access via proxy
    lineinfile:
      path: "/etc/environment"
      create: yes
      mode: 0644
      owner: root
      group: root
      line: "{{ item }}"
    become: True
    with_items:
    - "http_proxy={{ phe_http_proxy }}"
    - "https_proxy={{ phe_http_proxy }}"

  - name: Add proxy settings as profile
    copy:
      dest: "/etc/profile.d/phe_proxy.sh"
      mode: 0755
      owner: root
      group: root
      content: |
        export http_proxy={{ phe_http_proxy }}
        export https_proxy={{ phe_http_proxy }}
    become: True

  - name: Add proxy settings as profile
    copy:
      dest: "/etc/sudoers.d/proxy"
      mode: 0644
      owner: root
      group: root
      content: |
        Defaults env_keep += "http_proxy https_proxy"
    become: True


  roles:
    - role: cluster_hosts
    - role: resmo.ntp
      become: true

- hosts: infra_data
  tasks:

    - name: Ensure NFS server packages are installed
      package:
        name:
          - "nfs-utils"
        state: present
      become: true

    - set_fact:
        phe_home_export: "/srv{{ phe_home }}"
        phe_home_net_mask: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"
    - set_fact:
        phe_home_cidr: "{{ phe_home_net_mask | ipaddr('net') }}"

    - name: Ensure the home diretctory export point is created
      file:
        path: "/srv{{phe_home}}"
        state: directory
        owner: root
        group: root
        mode: 0755
      become: true

    - name: Add the export rule
      lineinfile:
        path: "/etc/exports"
        regexp: "^{{phe_home_export}} .*"
        line: "{{phe_home_export}} {{phe_home_cidr}}(rw,no_root_squash)"
        create: true
        owner: root
        group: root
        mode: 0750
      become: true

    - name: Ensure the NFS service is started
      service:
        name: nfs-server
        enabled: yes
        state: reloaded
      become: true

# Configure the Fortigate VPN (as best we can)
- hosts: infra_net
  roles:
    - role: fortigate_vpn
      fortigate_pkg: "{{ fortigate_pkg }}"
      fortigate_cfg: "{{ hpcdirect_fortigate }}"

- hosts: infra_user
  pre_tasks:
    - name: Ensure the PHE home directory mount point exists
      file:
        path: "{{ phe_home }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      become: true

    - name: Ensure the PHE home directory is mounted
      mount:
        path: "{{ phe_home }}"
        src: "{{hostvars['infra-data-0'].ansible_default_ipv4.address}}:{{hostvars['infra-data-0'].phe_home_export}}"
        fstype: nfs
        state: mounted
        boot: yes
        opts: "_netdev,noatime"
      become: true

    - name: Ensure RDO repo is present
      package:
        name: "centos-release-openstack-pike"
        state: present
      become: true
      when: ansible_os_family == "RedHat"

    - name: Install OpenStack client packages and dependencies
      package:
        name:
          - "python-openstackclient"
          - "python-heatclient"
          - "python-barbicanclient"
          - "python-virtualenv"
          - "git"
          - "gcc"
          - "python-devel"
        state: present
      become: true

    - name: Extract the infra_net IP
      set_fact:
        gw_ip: "{{ hostvars['infra-net-0']['ansible_default_ipv4']['address'] }}"

    - name: Read routing table
      command: "ip route list"
      become: True
      register: route_table

    - name: Configure routes for VPN
      command: "ip route add {{ item }} via {{ gw_ip }}"
      become: true
      when: route_table.stdout.find(item) == -1
      with_items:
        - "172.27.0.0/16"
        - "10.109.0.0/16"

  roles:
    - role: singleplatform-eng.users
      become: true
      users: "{{ phe_users }}"
      groups_to_create: "{{ phe_groups }}"

    - role: stackhpc.os-config
      os_config_content: "{{ cloud_config }}"
 
  post_tasks:
    - name: Assign cloudadm group access to clouds.yaml
      file:
        path: "/etc/openstack/clouds.yaml"
        owner: "root"
        group: "cloudadm"
        mode: 0640
        state: file
      become: true
